---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: acm-applications
  namespace: acm-configuration
  annotations:
    apps.open-cluster-management.io/reconcile-rate: high
spec:
  pathname: https://github.com/m4reshal/rhacm-applications
  type: Git
  secretRef:
    name: acm-github
