---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: ldap-group-sync-hub
  namespace: acm-subscriptions
spec:
  clusterSelector:
    matchLabels:
      vendor: OpenShift
      local-cluster: true
