---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: ldap-group-sync-hub
  namespace: acm-subscriptions
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: managed/ldap-group-sync/overlays/hub
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: ldap-group-sync-hub
spec:
  channel: acm-configuration/acm-applications
  placement:
    placementRef:
      name: ldap-group-sync-hub
      kind: PlacementRule
